#define DB_ENERGYSCAN "\
	CREATE TABLE ENERGYSCAN(\
		ID SERIAL PRIMARY KEY,\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		CH11 INT, CH12 INT, CH13 INT, CH14 INT, CH15 INT,\
		CH16 INT, CH17 INT, CH18 INT, CH19 INT, CH20 INT,\
		CH21 INT, CH22 INT, CH23 INT, CH24 INT, CH25 INT,\
		CH26 INT, CH27 INT, CH28 INT\
		)"

#define DB_LICENSE "\
	CREATE TABLE CONFIG (\
			ID SERIAL PRIMARY KEY,\
			TEXT	VARCHAR\
			)" 

#define DB_CONFIG "\
	CREATE TABLE CONFIG (\
			NAME 	varchar(20) PRIMARY KEY,\
			VALUE	varchar(50)\
			)" 

#define DB_JOURNAL "\
	CREATE TABLE JOURNAL (\
			ID SERIAL PRIMARY KEY,\
		   	TIMESTAMPZ TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		   	LEVEL VARCHAR(16) NOT NULL,\
		   	SOURCE VARCHAR(64) NOT NULL,\
		   	MESSAGE VARCHAR(250) NOT NULL\
			)" 

#define DB_VIRTUALSENSOR "\
	CREATE TABLE VIRTUALSENSOR(\
		ID SERIAL PRIMARY KEY,\
		COMMENT VARCHAR(250),\
		LOCATION VARCHAR(250),\
		NAME VARCHAR(32) NOT NULL UNIQUE,\
		TYPE VARCHAR(64) NOT NULL,\
		PARAM VARCHAR\
		)"

#define DB_NODELIST "\
	CREATE TABLE NODELIST (ID SERIAL PRIMARY KEY,\
		MAC CHAR(16) NOT NULL UNIQUE,\
		COMMENT VARCHAR(250),\
		LOCATION VARCHAR(250),\
		IPADDR INT NOT NULL UNIQUE,\
		NAME VARCHAR(32) NOT NULL UNIQUE,\
		NODE_TYPE VARCHAR(32),\
		NODE_VER VARCHAR(32)\
		)"

#define DB_NODE_STATISTIC "\
	CREATE TABLE NODE_STATISTIC(\
		ID SERIAL PRIMARY KEY,\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VBAT FLOAT,\
		RX_TIME FLOAT,\
		TX_TIME FLOAT,\
		CRC_ERROR INT,\
		CCA_ERROR INT,\
		UPTIME INT,\
		NODELIST_ID INT REFERENCES NODELIST(ID)\
		)"

#define DB_MEASURING_POINT "\
	CREATE TABLE MEASURING_POINT(\
		ID SERIAL PRIMARY KEY,\
		NODELIST_ID INT REFERENCES NODELIST(ID),\
		DATA_TYPE VARCHAR(16),\
		CHANNEL INT,\
		LOCATION VARCHAR(250),\
		COMMENT VARCHAR(250)\
		)"

#define DB_DATA_FLOAT "\
	CREATE TABLE DATA_FLOAT(\
		ID SERIAL PRIMARY KEY,\
		MEASURING_ID INT REFERENCES MEASURING_POINT(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE FLOAT\
		)"

#define DB_DATA_INT "\
	CREATE TABLE DATA_INT(\
		ID SERIAL PRIMARY KEY,\
		MEASURING_ID INT REFERENCES MEASURING_POINT(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE INT\
		)"

#define DB_DATA_BOOL "\
	CREATE TABLE DATA_BOOL(\
		ID SERIAL PRIMARY KEY,\
		MEASURING_ID INT REFERENCES MEASURING_POINT(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE BOOL\
		)"

#define DB_VIRT_DATA_FLOAT "\
	CREATE TABLE VIRT_DATA_FLOAT(\
		ID SERIAL PRIMARY KEY,\
		VIRTUALSENSOR_ID INT REFERENCES VIRTUALSENSOR(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE FLOAT\
		)"

#define DB_VIRT_DATA_INT "\
	CREATE TABLE VIRT_DATA_INT(\
		ID SERIAL PRIMARY KEY,\
		VIRTUALSENSOR_ID INT REFERENCES VIRTUALSENSOR(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE INT\
		)"

#define DB_VIRT_DATA_BOOL "\
	CREATE TABLE VIRT_DATA_BOOL(\
		ID SERIAL PRIMARY KEY,\
		VIRTUALSENSOR_ID INT REFERENCES VIRTUALSENSOR(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		VALUE BOOL\
		)"

#define DB_NODE_LAST_COMM "\
	CREATE TABLE NODE_LAST_COMM(\
		ID SERIAL PRIMARY KEY,\
		NODELIST_ID INT REFERENCES NODELIST(ID),\
		TIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		ACTIVE BOOL\
		)"

