#define DB_CONFIG "\
	CREATE TABLE CONFIG (\
			NAME 	varchar(20) PRIMARY KEY,\
			VALUE	varchar(50)\
			)" 

#define DB_JOURNAL "\
	CREATE TABLE JOURNAL (\
			ID SERIAL PRIMARY KEY,\
		   	TIMESTAMPZ TIMESTAMPTZ NOT NULL DEFAULT NOW(),\
		   	LEVEL VARCHAR(16) NOT NULL,\
		   	SOURCE VARCHAR(64) NOT NULL,\
		   	MESSAGE VARCHAR(250) NOT NULL\
			)" 

